[package]
name = "libmodcore"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
indexmap = "2.12.1"
regex = "1.12.2"
serde = "1.0.228"
serde_json = "1.0.145"
serde_yaml = "0.9.34"
shlex = "1.3.0"
textwrap = "0.16.2"
libsysinspect = { path = "../libsysinspect" }
