[package]
name = "run"
version = "0.2.0"
edition = "2024"

[dependencies]
libsysinspect = { path = "../../../libsysinspect" }
libmodcore = { path = "../../../libmodcore" }
serde = "1.0.228"
serde_json = "1.0.145"
serde_yaml = "0.9.34"
